### ISSUE TITLE
Add Firefox for iOS UA

### ISSUE THREAD

**Issue by AaronMT** [miketaylr/arewedetectableyet#9]
We have a stable string now (as far as I'm aware), it should be added to the site table and we can dig up any problems now.

**Comment by miketaylr** [comment]
Thanks! Will do.

**Comment by miketaylr** [comment]
OK, looks like the general format is:

`Mozilla/5.0 (<platform information>) AppleWebKit/<WebKit build number> (KHTML, like Gecko) FxiOS/<version number> Mobile/<mobile build number> Safari/<Safari build number>`

On my iPod touch, private build #18 is:
`Mozilla/5.0 (iPod Touch; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4`

**Comment by miketaylr** [comment]
Fixed in https://github.com/miketaylr/arewedetectableyet/commit/ca04e575a0196e1507d43c97d1935cfaeb5bfc86. The icon I used is probably not official, but whatever.

**Comment by miketaylr** [comment]
(will do the actual testing in the coming weeks)
